kind: Deployment
apiVersion: apps/v1
metadata:
  name: dont-give-up-client
  labels:
    app: dont-give-up-client
spec:
  selector:
    matchLabels:
      app: dont-give-up-client
  replicas: 1
  template:
    metadata:
      name: dont-give-up-client
      labels:
        app: dont-give-up-client
    spec:
      containers:
        - name: dont-give-up-client
          image: docker.io/ohcm0013/dont-give-up-client:latest
          imagePullPolicy: Always
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1024Mi

---
apiVersion: v1
kind: Service
metadata:
  name: dont-give-up-client
spec:
  type: ClusterIP
  selector:
    app: dont-give-up-client
  ports:
    - name: dont-give-up-client
      port: 8080
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dont-give-up-client
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  ingressClassName: nginx
  rules:
    - host: dont-give-up-client.165.192.105.60.nip.io
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: dont-give-up-client
                port:
                  number: 8080
